-- =============================================================================
-- Smart Weather System -- Supabase (PostgreSQL) schema
-- =============================================================================
-- Run once in the Supabase SQL Editor (or `psql "$SUPABASE_DB_URL" -f schema.sql`).
-- The script is idempotent: it can be re-run safely.
--
-- Contents
--   1. helper functions
--   2. users / admin_users (linked to Supabase Auth: auth.users)
--   3. weather + alerts + activity
--   4. agriculture
--   5. sensors
--   6. AI / prediction / experiments
--   7. admin audit log
--   8. indexes
--   9. Row Level Security + grants
--
-- Design notes
--   * The Flask backend connects with the database owner role (SUPABASE_DB_URL),
--     which bypasses RLS; it enforces authorisation itself. RLS protects the
--     public Supabase REST API (anon / authenticated keys) so the browser can
--     never read or write anything it should not.
--   * Legacy integer ids (farm_id, field_id, alert_id ...) are kept so existing
--     URLs / templates keep working. Users get a UUID primary key plus a stable
--     integer `user_number` (used by the legacy /user/<int> URLs).
--   * Event/audit times are timestamptz. Free-form planning dates typed into
--     forms (planted_date, expected_harvest_date, recommended_date) stay text
--     because the app accepts empty / non-ISO values there.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Helper functions
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END $$;

-- -----------------------------------------------------------------------------
-- 2. Users
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_number     bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    auth_user_id    uuid UNIQUE REFERENCES auth.users (id) ON DELETE CASCADE,
    username        text NOT NULL,
    email           text NOT NULL,
    location        text NOT NULL DEFAULT '',
    preferences     jsonb,
    role            text NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    is_active       boolean NOT NULL DEFAULT true,
    is_online       boolean NOT NULL DEFAULT false,   -- informational only; activity is derived from last_seen_at
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    last_seen_at    timestamptz,
    last_login_at   timestamptz,
    login_count     integer NOT NULL DEFAULT 0
);
COMMENT ON COLUMN public.users.auth_user_id IS
    'Supabase Auth account. NULL for legacy profiles created before login existed. For new accounts id = auth_user_id.';

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_key    ON public.users (lower(email));
CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_key ON public.users (lower(username));
CREATE INDEX IF NOT EXISTS users_last_seen_at_idx ON public.users (last_seen_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS users_created_at_idx   ON public.users (created_at DESC);
CREATE INDEX IF NOT EXISTS users_role_idx         ON public.users (role);

DROP TRIGGER IF EXISTS users_set_updated_at ON public.users;
CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON public.users
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.admin_users (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL UNIQUE REFERENCES public.users (id) ON DELETE CASCADE,
    role          text NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'super_admin')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz,
    is_active     boolean NOT NULL DEFAULT true
);

-- Profile <-> Supabase Auth linking ------------------------------------------------
-- Creates (or links) the public.users profile for an Auth account.
-- A pre-existing legacy profile with the same email is linked ONLY when the
-- email is confirmed, so nobody can claim someone else's profile by signing up
-- with their address.
CREATE OR REPLACE FUNCTION public.ensure_profile(p_auth_id uuid, p_email text, p_meta jsonb, p_confirmed boolean)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_id uuid;
    v_base text;
    v_candidate text;
    v_n integer := 0;
BEGIN
    SELECT id INTO v_id FROM public.users WHERE auth_user_id = p_auth_id;
    IF FOUND THEN RETURN v_id; END IF;

    SELECT id INTO v_id FROM public.users
     WHERE lower(email) = lower(p_email) AND auth_user_id IS NULL;
    IF FOUND THEN
        IF p_confirmed THEN
            UPDATE public.users SET auth_user_id = p_auth_id WHERE id = v_id;
            RETURN v_id;
        END IF;
        RETURN NULL;   -- will be linked once the email is confirmed
    END IF;

    v_base := coalesce(nullif(trim(p_meta ->> 'username'), ''), split_part(p_email, '@', 1));
    v_base := regexp_replace(v_base, '[^A-Za-z0-9_.-]', '', 'g');
    IF v_base = '' THEN v_base := 'user'; END IF;
    v_candidate := v_base;
    WHILE EXISTS (SELECT 1 FROM public.users WHERE lower(username) = lower(v_candidate)) LOOP
        v_n := v_n + 1;
        v_candidate := v_base || v_n::text;
    END LOOP;

    INSERT INTO public.users (id, auth_user_id, username, email, location)
    VALUES (p_auth_id, p_auth_id, v_candidate, lower(p_email), coalesce(p_meta ->> 'location', ''))
    ON CONFLICT DO NOTHING;
    RETURN p_auth_id;
END $$;

CREATE OR REPLACE FUNCTION public.handle_auth_user_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
    PERFORM public.ensure_profile(NEW.id, NEW.email, coalesce(NEW.raw_user_meta_data, '{}'::jsonb),
                                  NEW.email_confirmed_at IS NOT NULL);
    RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_auth_user_change();

DROP TRIGGER IF EXISTS on_auth_user_confirmed ON auth.users;
CREATE TRIGGER on_auth_user_confirmed AFTER UPDATE OF email_confirmed_at ON auth.users
    FOR EACH ROW WHEN (OLD.email_confirmed_at IS NULL AND NEW.email_confirmed_at IS NOT NULL)
    EXECUTE FUNCTION public.handle_auth_user_change();

-- RLS helper functions (SECURITY DEFINER so they can read users without recursion)
CREATE OR REPLACE FUNCTION public.current_profile_id()
RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
    SELECT id FROM public.users WHERE auth_user_id = auth.uid()
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
    SELECT EXISTS (
        SELECT 1
          FROM public.users u
          JOIN public.admin_users a ON a.user_id = u.id
         WHERE u.auth_user_id = auth.uid()
           AND u.role = 'admin' AND u.is_active AND a.is_active
    )
$$;

-- -----------------------------------------------------------------------------
-- 3. Weather, alerts, activity
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.weather_data (
    data_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location          text NOT NULL,
    temperature       double precision,
    humidity          double precision,
    pressure          double precision,
    wind_speed        double precision,
    weather_condition text,
    precipitation     double precision,
    recorded_at       timestamptz NOT NULL DEFAULT now(),
    sensor_id         text,
    data_source       text,
    sensor_timestamp  timestamptz,
    quality_flags     jsonb,
    validation_score  double precision,
    quality_label     text,
    cleaning_notes    jsonb,
    feature_blob      jsonb,
    decision_blob     jsonb,
    ingestion_mode    text
);

CREATE TABLE IF NOT EXISTS public.user_activities (
    activity_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             uuid REFERENCES public.users (id) ON DELETE CASCADE,
    activity_type       text NOT NULL,
    weather_condition   text,
    duration_minutes    integer,
    satisfaction_rating integer,
    activity_date       timestamptz NOT NULL DEFAULT now(),
    notes               text
);

CREATE TABLE IF NOT EXISTS public.weather_alerts (
    alert_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            uuid REFERENCES public.users (id) ON DELETE CASCADE,
    alert_type         text,
    severity           text,
    message            text,
    trigger_conditions jsonb,
    is_active          boolean NOT NULL DEFAULT true,
    created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.multi_hazard_alerts (
    alert_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location            text NOT NULL,
    hazard_type         text NOT NULL,
    risk_level          text NOT NULL,
    probability         double precision NOT NULL,
    message             text,
    recommended_actions jsonb,
    explanation         text,
    is_active           boolean NOT NULL DEFAULT true,
    created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.hazard_probabilities (
    prob_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id    bigint REFERENCES public.multi_hazard_alerts (alert_id) ON DELETE CASCADE,
    hazard_type text NOT NULL,
    probability double precision NOT NULL,
    risk_color  text NOT NULL
);

-- -----------------------------------------------------------------------------
-- 4. Agriculture   farm -> fields -> crop / weather / health / pests / irrigation / yield
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.farms (
    farm_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          text NOT NULL,
    owner_name    text NOT NULL,
    location      text NOT NULL,
    total_area_ha double precision NOT NULL DEFAULT 0,
    created_by    uuid REFERENCES public.users (id) ON DELETE SET NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.fields (
    field_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id         bigint NOT NULL REFERENCES public.farms (farm_id) ON DELETE CASCADE,
    name            text NOT NULL,
    area_ha         double precision NOT NULL,
    soil_type       text DEFAULT 'Loamy',
    irrigation_type text DEFAULT 'Drip',
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.crop_census (
    census_id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id              bigint NOT NULL REFERENCES public.fields (field_id) ON DELETE CASCADE,
    crop_type             text NOT NULL,
    area_ha               double precision NOT NULL,
    growth_stage          text DEFAULT 'Germination',
    planted_date          text,
    expected_harvest_date text,
    target_yield_ton_ha   double precision DEFAULT 3.0,
    season                text DEFAULT 'Rabi 2025-26',
    created_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.field_weather (
    fw_id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id          bigint NOT NULL REFERENCES public.fields (field_id) ON DELETE CASCADE,
    temperature       double precision,
    humidity          double precision,
    rainfall          double precision DEFAULT 0,
    wind_speed        double precision,
    pressure          double precision,
    solar_radiation   double precision DEFAULT 0,
    weather_condition text,
    recorded_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.crop_health (
    health_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id        bigint NOT NULL REFERENCES public.fields (field_id) ON DELETE CASCADE,
    health_score    double precision DEFAULT 100,
    heat_stress     double precision DEFAULT 0,
    frost_risk      double precision DEFAULT 0,
    drought_stress  double precision DEFAULT 0,
    excess_moisture double precision DEFAULT 0,
    recorded_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pest_risks (
    risk_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id        bigint NOT NULL REFERENCES public.fields (field_id) ON DELETE CASCADE,
    pest_type       text,
    risk_level      text DEFAULT 'low',
    warning_message text,
    recorded_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.irrigation_recommendations (
    rec_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id         bigint NOT NULL REFERENCES public.fields (field_id) ON DELETE CASCADE,
    recommended_date text,
    volume_mm        double precision,
    reason           text,
    is_done          boolean NOT NULL DEFAULT false,
    created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.yield_forecasts (
    forecast_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id             bigint NOT NULL REFERENCES public.fields (field_id) ON DELETE CASCADE,
    expected_yield_ton_ha double precision,
    target_yield_ton_ha   double precision,
    confidence            double precision DEFAULT 0.7,
    forecast_date         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.agri_alerts (
    alert_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id   bigint REFERENCES public.fields (field_id) ON DELETE CASCADE,
    farm_id    bigint REFERENCES public.farms (farm_id) ON DELETE CASCADE,
    alert_type text NOT NULL,
    severity   text DEFAULT 'medium',
    message    text NOT NULL,
    is_active  boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.agri_feedback (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop              text,
    predicted_disease text,
    actual_disease    text,
    is_correct        boolean NOT NULL DEFAULT false,
    is_simulated      boolean NOT NULL DEFAULT true,
    "timestamp"       timestamptz NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 5. Sensors
--    (no foreign key on field_id: devices may report ids that are not registered
--     as fields yet, and the ingestion pipeline must never reject a reading)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.raw_sensor_readings (
    reading_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id   text NOT NULL,
    sensor_type text NOT NULL,
    value       double precision NOT NULL,
    unit        text,
    "timestamp" timestamptz NOT NULL,
    field_id    bigint,
    received_at timestamptz NOT NULL DEFAULT now(),
    raw_payload jsonb
);

CREATE TABLE IF NOT EXISTS public.validated_sensor_readings (
    reading_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id         text NOT NULL,
    sensor_type       text NOT NULL,
    value             double precision NOT NULL,
    unit              text,
    quality_score     double precision DEFAULT 1.0,
    validation_reason text,
    "timestamp"       timestamptz NOT NULL,
    field_id          bigint,
    stored_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sensor_health (
    sensor_id         text PRIMARY KEY,
    last_reading_at   timestamptz,
    uptime_percentage double precision DEFAULT 100.0,
    quality_score_avg double precision DEFAULT 1.0,
    calibration_date  date,
    status            text NOT NULL DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS public.sensor_pipeline_logs (
    log_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id        text,
    source           text,
    location         text NOT NULL,
    sensor_timestamp timestamptz,
    quality_flags    jsonb,
    validation_score double precision,
    quality_label    text,
    raw_payload      jsonb,
    cleaned_payload  jsonb,
    feature_payload  jsonb,
    decision_payload jsonb,
    created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sensor_quality_metrics (
    metric_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id           text NOT NULL UNIQUE,
    total_records       integer NOT NULL DEFAULT 0,
    validation_failures integer NOT NULL DEFAULT 0,
    duplicate_records   integer NOT NULL DEFAULT 0,
    outlier_corrections integer NOT NULL DEFAULT 0,
    updated_at          timestamptz NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 6. AI / prediction / experiment tracking
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.prediction_quality_metrics (
    metric_id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location              text,
    sensor_id             text,
    predicted_temperature double precision,
    actual_temperature    double precision,
    error_abs             double precision,
    target_timestamp      timestamptz,
    status                text NOT NULL DEFAULT 'pending',
    updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.experiments (
    experiment_id   text PRIMARY KEY,
    experiment_name text NOT NULL,
    model_type      text NOT NULL,
    start_time      timestamptz NOT NULL DEFAULT now(),
    end_time        timestamptz,
    status          text DEFAULT 'running',
    description     text,
    tags            jsonb,
    parameters      jsonb,
    metrics         jsonb,
    artifacts       jsonb,
    git_commit      text,
    dataset_version text
);

CREATE TABLE IF NOT EXISTS public.model_versions (
    version_id     text PRIMARY KEY,
    experiment_id  text NOT NULL REFERENCES public.experiments (experiment_id) ON DELETE CASCADE,
    model_name     text NOT NULL,
    version_number text NOT NULL,
    model_path     text NOT NULL,
    metrics        jsonb,
    created_at     timestamptz NOT NULL DEFAULT now(),
    is_production  boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.dataset_versions (
    version_id     text PRIMARY KEY,
    dataset_name   text NOT NULL,
    version_number text NOT NULL,
    data_path      text NOT NULL,
    row_count      integer,
    column_count   integer,
    created_at     timestamptz NOT NULL DEFAULT now(),
    checksum       text
);

-- -----------------------------------------------------------------------------
-- 7. Admin audit log (who did what in the admin panel)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admin_audit_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id    uuid REFERENCES public.users (id) ON DELETE SET NULL,
    action      text NOT NULL,
    target_type text,
    target_id   text,
    details     jsonb,
    ip_address  text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 8. Indexes (only columns that are filtered / sorted / joined on)
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS weather_data_location_idx    ON public.weather_data (location);
CREATE INDEX IF NOT EXISTS weather_data_recorded_at_idx ON public.weather_data (recorded_at DESC);
CREATE INDEX IF NOT EXISTS weather_data_sensor_id_idx   ON public.weather_data (sensor_id);

CREATE INDEX IF NOT EXISTS user_activities_user_id_idx       ON public.user_activities (user_id);
CREATE INDEX IF NOT EXISTS user_activities_activity_date_idx ON public.user_activities (activity_date DESC);

CREATE INDEX IF NOT EXISTS weather_alerts_user_id_idx    ON public.weather_alerts (user_id);
CREATE INDEX IF NOT EXISTS weather_alerts_is_active_idx  ON public.weather_alerts (is_active);
CREATE INDEX IF NOT EXISTS weather_alerts_severity_idx   ON public.weather_alerts (severity);
CREATE INDEX IF NOT EXISTS weather_alerts_created_at_idx ON public.weather_alerts (created_at DESC);

CREATE INDEX IF NOT EXISTS multi_hazard_alerts_active_idx ON public.multi_hazard_alerts (is_active, created_at DESC);
CREATE INDEX IF NOT EXISTS hazard_probabilities_alert_idx ON public.hazard_probabilities (alert_id);

CREATE INDEX IF NOT EXISTS farms_created_at_idx ON public.farms (created_at DESC);
CREATE INDEX IF NOT EXISTS fields_farm_id_idx   ON public.fields (farm_id);
CREATE INDEX IF NOT EXISTS crop_census_field_idx   ON public.crop_census (field_id, created_at DESC);
CREATE INDEX IF NOT EXISTS field_weather_field_idx ON public.field_weather (field_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS crop_health_field_idx   ON public.crop_health (field_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS pest_risks_field_idx    ON public.pest_risks (field_id);
CREATE INDEX IF NOT EXISTS irrigation_rec_field_idx ON public.irrigation_recommendations (field_id) WHERE NOT is_done;
CREATE INDEX IF NOT EXISTS yield_forecasts_field_idx ON public.yield_forecasts (field_id, forecast_date DESC);
CREATE INDEX IF NOT EXISTS agri_alerts_active_idx   ON public.agri_alerts (is_active, created_at DESC);
CREATE INDEX IF NOT EXISTS agri_alerts_field_idx    ON public.agri_alerts (field_id);

CREATE INDEX IF NOT EXISTS raw_sensor_sensor_ts_idx   ON public.raw_sensor_readings (sensor_id, "timestamp" DESC);
CREATE INDEX IF NOT EXISTS raw_sensor_field_idx       ON public.raw_sensor_readings (field_id);
CREATE INDEX IF NOT EXISTS raw_sensor_received_idx    ON public.raw_sensor_readings (received_at DESC);
CREATE INDEX IF NOT EXISTS validated_sensor_sensor_ts_idx ON public.validated_sensor_readings (sensor_id, "timestamp" DESC);
CREATE INDEX IF NOT EXISTS validated_sensor_type_ts_idx   ON public.validated_sensor_readings (sensor_type, "timestamp" DESC);
CREATE INDEX IF NOT EXISTS validated_sensor_field_idx     ON public.validated_sensor_readings (field_id);
CREATE INDEX IF NOT EXISTS sensor_health_status_idx   ON public.sensor_health (status);
CREATE INDEX IF NOT EXISTS sensor_pipeline_logs_sensor_ts_idx ON public.sensor_pipeline_logs (sensor_id, sensor_timestamp);
CREATE INDEX IF NOT EXISTS sensor_pipeline_logs_created_idx   ON public.sensor_pipeline_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS prediction_metrics_location_idx ON public.prediction_quality_metrics (location);
CREATE INDEX IF NOT EXISTS prediction_metrics_updated_idx  ON public.prediction_quality_metrics (updated_at DESC);
CREATE INDEX IF NOT EXISTS prediction_metrics_pending_idx  ON public.prediction_quality_metrics (target_timestamp) WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS agri_feedback_timestamp_idx ON public.agri_feedback ("timestamp" DESC);
CREATE INDEX IF NOT EXISTS admin_audit_log_created_idx ON public.admin_audit_log (created_at DESC);

-- -----------------------------------------------------------------------------
-- 9. Row Level Security
--    * RLS is ENABLED on every table (never disabled to "make things work").
--    * anon has no access at all.
--    * authenticated users: own profile / own alerts / own activity, read-only
--      access to the shared weather + agriculture data, no writes.
--    * admins (public.is_admin()) can read everything.
--    * The Flask backend uses the database owner connection and enforces its
--      own authorisation; the service-role key is never sent to the browser.
-- -----------------------------------------------------------------------------
REVOKE ALL ON ALL TABLES    IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.ensure_profile(uuid, text, jsonb, boolean) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_auth_user_change() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.current_profile_id() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.current_profile_id() TO authenticated;
GRANT  EXECUTE ON FUNCTION public.is_admin() TO authenticated;

DO $$
DECLARE t text;
BEGIN
    -- every table: RLS on
    FOREACH t IN ARRAY ARRAY[
        'users','admin_users','weather_data','user_activities','weather_alerts',
        'multi_hazard_alerts','hazard_probabilities','farms','fields','crop_census',
        'field_weather','crop_health','pest_risks','irrigation_recommendations',
        'yield_forecasts','agri_alerts','agri_feedback','raw_sensor_readings',
        'validated_sensor_readings','sensor_health','sensor_pipeline_logs',
        'sensor_quality_metrics','prediction_quality_metrics','experiments',
        'model_versions','dataset_versions','admin_audit_log']
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_admin_read', t);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (public.is_admin())',
                       t || '_admin_read', t);
        EXECUTE format('GRANT SELECT ON public.%I TO authenticated', t);
    END LOOP;

    -- shared, non-personal data: readable by any signed-in user
    FOREACH t IN ARRAY ARRAY[
        'weather_data','multi_hazard_alerts','hazard_probabilities','farms','fields',
        'crop_census','field_weather','crop_health','pest_risks',
        'irrigation_recommendations','yield_forecasts','agri_alerts']
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_read_authenticated', t);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (true)',
                       t || '_read_authenticated', t);
    END LOOP;

    -- personal data: owner only
    FOREACH t IN ARRAY ARRAY['user_activities','weather_alerts']
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_read_own', t);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (user_id = public.current_profile_id())',
                       t || '_read_own', t);
    END LOOP;
END $$;

-- users: a signed-in user sees and edits ONLY their own profile, and only these columns
-- (role / is_active / login counters can never be changed through the public API).
DROP POLICY IF EXISTS users_read_own ON public.users;
CREATE POLICY users_read_own ON public.users FOR SELECT TO authenticated
    USING (auth_user_id = auth.uid());

DROP POLICY IF EXISTS users_update_own ON public.users;
CREATE POLICY users_update_own ON public.users FOR UPDATE TO authenticated
    USING (auth_user_id = auth.uid()) WITH CHECK (auth_user_id = auth.uid());
GRANT UPDATE (username, location, preferences) ON public.users TO authenticated;

-- admin_users has no write policy for anyone: only the backend (owner role) can change it.
