tools:
    shell:
        allow:
            - cd *
            - git status
            - echo *
            - git branch *
            - git remote *
            - ls *
            - find *
            - pwd
            - python *
            - where python3
            - where py
            - .venv\Scripts\python.exe *
            - cat *
            - Select-Object *
            - file *
            - Get-Command py *
            - Get-Command python3 *
            - py *
            - Get-ChildItem *
            - git log *
            - mkdir *
            - Remove-Item *
            - git diff *
            - git status *
            - git add *
            - git commit *
            - git push origin *
            - curl *
            - Select-String *
            - netstat *
            - findstr *
            - npm *
            - node *
            - Out-String *
            - head *
            - dir *
            - where python
            - D:\SWS\Smart_weather_system\.venv\Scripts\python.exe *
            - Sort-Object Length *
            - Get-Command python
            - Get-Module *
            - '"C:\Program Files\Python311\python.exe" *'
            - Get-Content *
            - ForEach-Object { *
            - Where-Object { *
            - git *
            - Format-Table *
            - .venv\Scripts\python *
            - Write-Host "---"
            - wc *
            - Measure-Object *
            - $OutputEncoding *
            - Out-File *
            - Write-Host "Done extracting all"
            - Test-Path *
            - Test-Path LICENSE
            - Sort-Object
            - cmd *
            - pip install torch torchvision *
            - tail *
            - out-file *
            - type *
            - grep *
            - Get-Command python *
            - $env:PYTHONIOENCODING *
